#!/usr/bin/env python
# -*- coding: iso-8859-1 -*- 

import serial
import time

ser = serial.Serial()
ser.baudrate = 300
ser.port = '/dev/ttyUSB0'     
ser.timeout = 20 #20
ser.parity = serial.PARITY_EVEN
ser.stopbits = serial.STOPBITS_ONE
ser.bytesize = serial.SEVENBITS
ser.open()
ser.isOpen()
print("open")
time.sleep(2)
ser.write("/?!")
#ser.write("?")
#ser.write("!")
print("written")
time.sleep(2)
ser.write("\r\n")
line = ser.readline(eol='!')
print line
ser.close()
