#!/usr/bin/env python
# -*- coding: iso-8859-1 -*- 

import serial
import time
import sqlite3
import re

connection = sqlite3.connect('/var/www/zaehler/test1.db')
cursor = connection.cursor()
extrakt = []
ss = r'(0\.0\.0|0\.9\.1|0\.9\.2|1\.6\.1|1\.8\.1)\(([0-9\.]+)'

ser = serial.Serial()
ser.baudrate = 300
ser.port = '/dev/ttyUSB4'     
ser.timeout = 20 
ser.parity = serial.PARITY_EVEN
ser.stopbits = serial.STOPBITS_ONE
ser.bytesize = serial.SEVENBITS
ser.open()
ser.isOpen()
print("open")
time.sleep(2)
ser.write("/?!")
print("written")
time.sleep(2)
ser.write("\r\n")
#line = ser.readline(eol='!')
#print line
#ser.close()
time.sleep(2)
while (True):
    line = ser.readline(eol='!')
    if (len(line) == 0):
        break
    match = re.search(ss, line)
    if match: 
        version,value = match.groups() 
        extrakt.append(value)

print extrakt []
cursor.execute('INSERT INTO energielog (sernr, time, date, peak, kwh) values (?, ?, ?, ?, ?)', extrakt)

connection.commit()
ser.close()
cursor.close()
connection.close()
