#!/usr/bin/env python
# -*- coding: iso-8859-1 -*- 

import serial
import time
import sqlite3
import re

fd = open('/home/frank/logEn', 'w')
ser = serial.Serial()
ser.baudrate = 300
ser.port = '/dev/ttyUSB4'     
ser.timeout = 20 
ser.parity = serial.PARITY_EVEN
ser.stopbits = serial.STOPBITS_ONE
ser.bytesize = serial.SEVENBITS
ser.open()
ser.isOpen()
print("open")
time.sleep(2)
ser.write("/?!")
print("written")
time.sleep(2)
ser.write("\r\n")
line = ser.readline(eol='!')
fd.write(line)
#print line
ser.close()
fd.close()
#----------
time.sleep(5)
#-------------------------sqlite Einbindung 
conn = sqlite3.connect('/var/www/zaehler/inc/db/zaehler.sqlite')
cursor = conn.cursor()
#-------------------------Vorbereitung Liste für Weitergabe Messwerte
extrakt = []

fs = open('/home/frank/logEn', 'r')
for line in fs:
	match = re.search(r'(0\.0\.0|0\.9\.1|0\.9\.2|1\.6\.1|1\.8\.1)\(([0-9\.]+)', line)
	if match: 
		version,value = match.groups() 
		extrakt.append(value)
#print extrakt
cursor.execute('INSERT INTO energielog (sernr, time, date, peak, kwh) values (?, ?, ?, ?, ?)', extrakt)

# Save (commit) the changes
conn.commit()

#ser.close()
cursor.close()
conn.close()
fs.close()
