#!/usr/bin/env python
# -*- coding: iso-8859-1 -*- 

#import serial
#import time
import re
import sqlite3

#--------------------------serielle USB-Schnittstelle öffnen
#ser = serial.Serial()
#ser.baudrate = 300
#ser.port = '/dev/ttyUSB0'     
#ser.timeout = 20 #20
#ser.parity = serial.PARITY_EVEN
#ser.stopbits = serial.STOPBITS_ONE
#ser.bytesize = serial.SEVENBITS

#ser.open()
#ser.isOpen()

#--------------------------Zählerabfrage initiieren mit /?!
#time.sleep(2)
#ser.write("/?!")
#time.sleep(0.01)     #1ms = 0.001 war im cutecom eingestellt und hat funktioniert
#ser.write("\r\n")       #CR LF? \r\n
#time.sleep(2)


#-------------------------sqlite Einbindung 
conn = sqlite3.connect('/var/www/zaehler/inc/db/zaehler.sqlite')
cursor = conn.cursor()
#-------------------------Vorbereitung Liste für Weitergabe Messwerte
extrakt = []

#for line in ser.readline(eol='!'):
with open("/home/frank/logEn") as fp:
	for line in fp:
		match = re.search(r'(0\.0\.0|0\.9\.1|0\.9\.2|1\.6\.1|1\.8\.1)\(([0-9\.]+)', line)
		if match: 
			version,value = match.groups() 
			extrakt.append(value)
#print extrakt
cursor.execute('INSERT INTO energielog (sernr, time, date, peak, kwh) values (?, ?, ?, ?, ?)', extrakt)

# Save (commit) the changes--laeuft so!!---
conn.commit()

#ser.close()
cursor.close()
conn.close()
